// Package kodit provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package kodit

const (
	APIKeyAuthScopes = "APIKeyAuth.Scopes"
)

// Defines values for DtoTrackingMode.
const (
	TrackingModeBranch DtoTrackingMode = "branch"
	TrackingModeTag    DtoTrackingMode = "tag"
)

// DtoCommitAttributes defines model for dto.CommitAttributes.
type DtoCommitAttributes struct {
	Author          *string `json:"author,omitempty"`
	CommitSha       *string `json:"commit_sha,omitempty"`
	Date            *string `json:"date,omitempty"`
	Message         *string `json:"message,omitempty"`
	ParentCommitSha *string `json:"parent_commit_sha,omitempty"`
}

// DtoCommitData defines model for dto.CommitData.
type DtoCommitData struct {
	Attributes *DtoCommitAttributes `json:"attributes,omitempty"`
	Id         *string              `json:"id,omitempty"`
	Type       *string              `json:"type,omitempty"`
}

// DtoCommitJSONAPIListResponse defines model for dto.CommitJSONAPIListResponse.
type DtoCommitJSONAPIListResponse struct {
	Data  *[]DtoCommitData `json:"data,omitempty"`
	Links *JsonapiLinks    `json:"links,omitempty"`
	Meta  *JsonapiMeta     `json:"meta,omitempty"`
}

// DtoCommitJSONAPIResponse defines model for dto.CommitJSONAPIResponse.
type DtoCommitJSONAPIResponse struct {
	Data *DtoCommitData `json:"data,omitempty"`
}

// DtoEnrichmentAttributes defines model for dto.EnrichmentAttributes.
type DtoEnrichmentAttributes struct {
	Content   *string `json:"content,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Subtype   *string `json:"subtype,omitempty"`
	Type      *string `json:"type,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// DtoEnrichmentData defines model for dto.EnrichmentData.
type DtoEnrichmentData struct {
	Attributes *DtoEnrichmentAttributes `json:"attributes,omitempty"`
	Id         *string                  `json:"id,omitempty"`
	Type       *string                  `json:"type,omitempty"`
}

// DtoEnrichmentJSONAPIListResponse defines model for dto.EnrichmentJSONAPIListResponse.
type DtoEnrichmentJSONAPIListResponse struct {
	Data  *[]DtoEnrichmentData `json:"data,omitempty"`
	Links *JsonapiLinks        `json:"links,omitempty"`
	Meta  *JsonapiMeta         `json:"meta,omitempty"`
}

// DtoEnrichmentJSONAPIResponse defines model for dto.EnrichmentJSONAPIResponse.
type DtoEnrichmentJSONAPIResponse struct {
	Data *DtoEnrichmentData `json:"data,omitempty"`
}

// DtoEnrichmentSchema defines model for dto.EnrichmentSchema.
type DtoEnrichmentSchema struct {
	Content *string `json:"content,omitempty"`
	Type    *string `json:"type,omitempty"`
}

// DtoEnrichmentUpdateAttributes defines model for dto.EnrichmentUpdateAttributes.
type DtoEnrichmentUpdateAttributes struct {
	Content *string `json:"content,omitempty"`
}

// DtoEnrichmentUpdateData defines model for dto.EnrichmentUpdateData.
type DtoEnrichmentUpdateData struct {
	Attributes *DtoEnrichmentUpdateAttributes `json:"attributes,omitempty"`
	Type       *string                        `json:"type,omitempty"`
}

// DtoEnrichmentUpdateRequest defines model for dto.EnrichmentUpdateRequest.
type DtoEnrichmentUpdateRequest struct {
	Data *DtoEnrichmentUpdateData `json:"data,omitempty"`
}

// DtoFileAttributes defines model for dto.FileAttributes.
type DtoFileAttributes struct {
	BlobSha   *string `json:"blob_sha,omitempty"`
	Extension *string `json:"extension,omitempty"`
	MimeType  *string `json:"mime_type,omitempty"`
	Path      *string `json:"path,omitempty"`
	Size      *int    `json:"size,omitempty"`
}

// DtoFileData defines model for dto.FileData.
type DtoFileData struct {
	Attributes *DtoFileAttributes `json:"attributes,omitempty"`
	Id         *string            `json:"id,omitempty"`
	Type       *string            `json:"type,omitempty"`
}

// DtoFileJSONAPIListResponse defines model for dto.FileJSONAPIListResponse.
type DtoFileJSONAPIListResponse struct {
	Data  *[]DtoFileData `json:"data,omitempty"`
	Links *JsonapiLinks  `json:"links,omitempty"`
	Meta  *JsonapiMeta   `json:"meta,omitempty"`
}

// DtoFileJSONAPIResponse defines model for dto.FileJSONAPIResponse.
type DtoFileJSONAPIResponse struct {
	Data *DtoFileData `json:"data,omitempty"`
}

// DtoGitFileSchema defines model for dto.GitFileSchema.
type DtoGitFileSchema struct {
	BlobSha  *string `json:"blob_sha,omitempty"`
	MimeType *string `json:"mime_type,omitempty"`
	Path     *string `json:"path,omitempty"`
	Size     *int    `json:"size,omitempty"`
}

// DtoRepositoryAttributes defines model for dto.RepositoryAttributes.
type DtoRepositoryAttributes struct {
	ClonedPath     *string `json:"cloned_path,omitempty"`
	CreatedAt      *string `json:"created_at,omitempty"`
	LastScannedAt  *string `json:"last_scanned_at,omitempty"`
	NumBranches    *int    `json:"num_branches,omitempty"`
	NumCommits     *int    `json:"num_commits,omitempty"`
	NumTags        *int    `json:"num_tags,omitempty"`
	RemoteUri      *string `json:"remote_uri,omitempty"`
	TrackingBranch *string `json:"tracking_branch,omitempty"`
	UpdatedAt      *string `json:"updated_at,omitempty"`
}

// DtoRepositoryBranchData defines model for dto.RepositoryBranchData.
type DtoRepositoryBranchData struct {
	CommitCount *int    `json:"commit_count,omitempty"`
	IsDefault   *bool   `json:"is_default,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// DtoRepositoryCommitData defines model for dto.RepositoryCommitData.
type DtoRepositoryCommitData struct {
	Author    *string `json:"author,omitempty"`
	Message   *string `json:"message,omitempty"`
	Sha       *string `json:"sha,omitempty"`
	Timestamp *string `json:"timestamp,omitempty"`
}

// DtoRepositoryCreateAttributes defines model for dto.RepositoryCreateAttributes.
type DtoRepositoryCreateAttributes struct {
	RemoteUri *string `json:"remote_uri,omitempty"`
}

// DtoRepositoryCreateData defines model for dto.RepositoryCreateData.
type DtoRepositoryCreateData struct {
	Attributes *DtoRepositoryCreateAttributes `json:"attributes,omitempty"`
	Type       *string                        `json:"type,omitempty"`
}

// DtoRepositoryCreateRequest defines model for dto.RepositoryCreateRequest.
type DtoRepositoryCreateRequest struct {
	Data *DtoRepositoryCreateData `json:"data,omitempty"`
}

// DtoRepositoryData defines model for dto.RepositoryData.
type DtoRepositoryData struct {
	Attributes *DtoRepositoryAttributes `json:"attributes,omitempty"`
	Id         *string                  `json:"id,omitempty"`
	Type       *string                  `json:"type,omitempty"`
}

// DtoRepositoryDetailsResponse defines model for dto.RepositoryDetailsResponse.
type DtoRepositoryDetailsResponse struct {
	Branches      *[]DtoRepositoryBranchData `json:"branches,omitempty"`
	Data          *DtoRepositoryData         `json:"data,omitempty"`
	RecentCommits *[]DtoRepositoryCommitData `json:"recent_commits,omitempty"`
}

// DtoRepositoryListResponse defines model for dto.RepositoryListResponse.
type DtoRepositoryListResponse struct {
	Data  *[]DtoRepositoryData `json:"data,omitempty"`
	Links *JsonapiLinks        `json:"links,omitempty"`
	Meta  *JsonapiMeta         `json:"meta,omitempty"`
}

// DtoRepositoryResponse defines model for dto.RepositoryResponse.
type DtoRepositoryResponse struct {
	Data *DtoRepositoryData `json:"data,omitempty"`
}

// DtoRepositoryStatusSummaryAttributes defines model for dto.RepositoryStatusSummaryAttributes.
type DtoRepositoryStatusSummaryAttributes struct {
	Message   *string `json:"message,omitempty"`
	Status    *string `json:"status,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// DtoRepositoryStatusSummaryData defines model for dto.RepositoryStatusSummaryData.
type DtoRepositoryStatusSummaryData struct {
	Attributes *DtoRepositoryStatusSummaryAttributes `json:"attributes,omitempty"`
	Id         *string                               `json:"id,omitempty"`
	Type       *string                               `json:"type,omitempty"`
}

// DtoRepositoryStatusSummaryResponse defines model for dto.RepositoryStatusSummaryResponse.
type DtoRepositoryStatusSummaryResponse struct {
	Data *DtoRepositoryStatusSummaryData `json:"data,omitempty"`
}

// DtoSearchAttributes defines model for dto.SearchAttributes.
type DtoSearchAttributes struct {
	Code     *string           `json:"code,omitempty"`
	Filters  *DtoSearchFilters `json:"filters,omitempty"`
	Keywords *[]string         `json:"keywords,omitempty"`
	Limit    *int              `json:"limit,omitempty"`
	Text     *string           `json:"text,omitempty"`
}

// DtoSearchData defines model for dto.SearchData.
type DtoSearchData struct {
	Attributes *DtoSearchAttributes `json:"attributes,omitempty"`
	Type       *string              `json:"type,omitempty"`
}

// DtoSearchFilters defines model for dto.SearchFilters.
type DtoSearchFilters struct {
	Authors            *[]string `json:"authors,omitempty"`
	CommitSha          *[]string `json:"commit_sha,omitempty"`
	EndDate            *string   `json:"end_date,omitempty"`
	EnrichmentSubtypes *[]string `json:"enrichment_subtypes,omitempty"`
	EnrichmentTypes    *[]string `json:"enrichment_types,omitempty"`
	FilePatterns       *[]string `json:"file_patterns,omitempty"`
	Languages          *[]string `json:"languages,omitempty"`
	Sources            *[]string `json:"sources,omitempty"`
	StartDate          *string   `json:"start_date,omitempty"`
}

// DtoSearchRequest defines model for dto.SearchRequest.
type DtoSearchRequest struct {
	Data *DtoSearchData `json:"data,omitempty"`
}

// DtoSearchResponse defines model for dto.SearchResponse.
type DtoSearchResponse struct {
	Data *[]DtoSnippetData `json:"data,omitempty"`
}

// DtoSnippetAttributes defines model for dto.SnippetAttributes.
type DtoSnippetAttributes struct {
	Content        *DtoSnippetContentSchema `json:"content,omitempty"`
	CreatedAt      *string                  `json:"created_at,omitempty"`
	DerivesFrom    *[]DtoGitFileSchema      `json:"derives_from,omitempty"`
	Enrichments    *[]DtoEnrichmentSchema   `json:"enrichments,omitempty"`
	OriginalScores *[]float32               `json:"original_scores,omitempty"`
	UpdatedAt      *string                  `json:"updated_at,omitempty"`
}

// DtoSnippetContentSchema defines model for dto.SnippetContentSchema.
type DtoSnippetContentSchema struct {
	Language *string `json:"language,omitempty"`
	Value    *string `json:"value,omitempty"`
}

// DtoSnippetData defines model for dto.SnippetData.
type DtoSnippetData struct {
	Attributes *DtoSnippetAttributes `json:"attributes,omitempty"`
	Id         *string               `json:"id,omitempty"`
	Links      *DtoSnippetLinks      `json:"links,omitempty"`
	Type       *string               `json:"type,omitempty"`
}

// DtoSnippetLinks defines model for dto.SnippetLinks.
type DtoSnippetLinks struct {
	Commit     *string `json:"commit,omitempty"`
	File       *string `json:"file,omitempty"`
	Repository *string `json:"repository,omitempty"`
}

// DtoSnippetListResponse defines model for dto.SnippetListResponse.
type DtoSnippetListResponse struct {
	Data  *[]DtoSnippetData `json:"data,omitempty"`
	Links *JsonapiLinks     `json:"links,omitempty"`
	Meta  *JsonapiMeta      `json:"meta,omitempty"`
}

// DtoTagAttributes defines model for dto.TagAttributes.
type DtoTagAttributes struct {
	IsVersionTag    *bool   `json:"is_version_tag,omitempty"`
	Name            *string `json:"name,omitempty"`
	TargetCommitSha *string `json:"target_commit_sha,omitempty"`
}

// DtoTagData defines model for dto.TagData.
type DtoTagData struct {
	Attributes *DtoTagAttributes `json:"attributes,omitempty"`
	Id         *string           `json:"id,omitempty"`
	Type       *string           `json:"type,omitempty"`
}

// DtoTagJSONAPIListResponse defines model for dto.TagJSONAPIListResponse.
type DtoTagJSONAPIListResponse struct {
	Data  *[]DtoTagData `json:"data,omitempty"`
	Links *JsonapiLinks `json:"links,omitempty"`
	Meta  *JsonapiMeta  `json:"meta,omitempty"`
}

// DtoTagJSONAPIResponse defines model for dto.TagJSONAPIResponse.
type DtoTagJSONAPIResponse struct {
	Data *DtoTagData `json:"data,omitempty"`
}

// DtoTaskAttributes defines model for dto.TaskAttributes.
type DtoTaskAttributes struct {
	CreatedAt *string     `json:"created_at,omitempty"`
	Payload   interface{} `json:"payload,omitempty"`
	Priority  *int        `json:"priority,omitempty"`
	Type      *string     `json:"type,omitempty"`
	UpdatedAt *string     `json:"updated_at,omitempty"`
}

// DtoTaskData defines model for dto.TaskData.
type DtoTaskData struct {
	Attributes *DtoTaskAttributes `json:"attributes,omitempty"`
	Id         *string            `json:"id,omitempty"`
	Type       *string            `json:"type,omitempty"`
}

// DtoTaskListResponse defines model for dto.TaskListResponse.
type DtoTaskListResponse struct {
	Data  *[]DtoTaskData `json:"data,omitempty"`
	Links *JsonapiLinks  `json:"links,omitempty"`
	Meta  *JsonapiMeta   `json:"meta,omitempty"`
}

// DtoTaskResponse defines model for dto.TaskResponse.
type DtoTaskResponse struct {
	Data *DtoTaskData `json:"data,omitempty"`
}

// DtoTaskStatusAttributes defines model for dto.TaskStatusAttributes.
type DtoTaskStatusAttributes struct {
	CreatedAt *string  `json:"created_at,omitempty"`
	Current   *int     `json:"current,omitempty"`
	Error     *string  `json:"error,omitempty"`
	Message   *string  `json:"message,omitempty"`
	Progress  *float32 `json:"progress,omitempty"`
	State     *string  `json:"state,omitempty"`
	Step      *string  `json:"step,omitempty"`
	Total     *int     `json:"total,omitempty"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
}

// DtoTaskStatusData defines model for dto.TaskStatusData.
type DtoTaskStatusData struct {
	Attributes *DtoTaskStatusAttributes `json:"attributes,omitempty"`
	Id         *string                  `json:"id,omitempty"`
	Type       *string                  `json:"type,omitempty"`
}

// DtoTaskStatusListResponse defines model for dto.TaskStatusListResponse.
type DtoTaskStatusListResponse struct {
	Data  *[]DtoTaskStatusData `json:"data,omitempty"`
	Links *JsonapiLinks        `json:"links,omitempty"`
	Meta  *JsonapiMeta         `json:"meta,omitempty"`
}

// DtoTrackingConfigAttributes defines model for dto.TrackingConfigAttributes.
type DtoTrackingConfigAttributes struct {
	Mode  *DtoTrackingMode `json:"mode,omitempty"`
	Value *string          `json:"value,omitempty"`
}

// DtoTrackingConfigData defines model for dto.TrackingConfigData.
type DtoTrackingConfigData struct {
	Attributes *DtoTrackingConfigAttributes `json:"attributes,omitempty"`
	Type       *string                      `json:"type,omitempty"`
}

// DtoTrackingConfigResponse defines model for dto.TrackingConfigResponse.
type DtoTrackingConfigResponse struct {
	Data *DtoTrackingConfigData `json:"data,omitempty"`
}

// DtoTrackingConfigUpdateAttributes defines model for dto.TrackingConfigUpdateAttributes.
type DtoTrackingConfigUpdateAttributes struct {
	Mode  *DtoTrackingMode `json:"mode,omitempty"`
	Value *string          `json:"value,omitempty"`
}

// DtoTrackingConfigUpdateData defines model for dto.TrackingConfigUpdateData.
type DtoTrackingConfigUpdateData struct {
	Attributes *DtoTrackingConfigUpdateAttributes `json:"attributes,omitempty"`
	Type       *string                            `json:"type,omitempty"`
}

// DtoTrackingConfigUpdateRequest defines model for dto.TrackingConfigUpdateRequest.
type DtoTrackingConfigUpdateRequest struct {
	Data *DtoTrackingConfigUpdateData `json:"data,omitempty"`
}

// DtoTrackingMode defines model for dto.TrackingMode.
type DtoTrackingMode string

// JsonapiLinks defines model for jsonapi.Links.
type JsonapiLinks struct {
	First *string `json:"first,omitempty"`
	Last  *string `json:"last,omitempty"`
	Next  *string `json:"next,omitempty"`
	Prev  *string `json:"prev,omitempty"`
	Self  *string `json:"self,omitempty"`
}

// JsonapiMeta defines model for jsonapi.Meta.
type JsonapiMeta map[string]interface{}

// MiddlewareJSONAPIError defines model for middleware.JSONAPIError.
type MiddlewareJSONAPIError struct {
	Detail *string `json:"detail,omitempty"`
	Id     *string `json:"id,omitempty"`
	Status *string `json:"status,omitempty"`
	Title  *string `json:"title,omitempty"`
}

// MiddlewareJSONAPIErrorResponse defines model for middleware.JSONAPIErrorResponse.
type MiddlewareJSONAPIErrorResponse struct {
	Errors *[]MiddlewareJSONAPIError `json:"errors,omitempty"`
}

// GetEnrichmentsParams defines parameters for GetEnrichments.
type GetEnrichmentsParams struct {
	// EnrichmentType Filter by enrichment type
	EnrichmentType *string `form:"enrichment_type,omitempty" json:"enrichment_type,omitempty"`

	// EnrichmentSubtype Filter by enrichment subtype
	EnrichmentSubtype *string `form:"enrichment_subtype,omitempty" json:"enrichment_subtype,omitempty"`

	// Page Page number (default: 1)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Results per page (default: 20, max: 100)
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetQueueParams defines parameters for GetQueue.
type GetQueueParams struct {
	// Page Page number (default: 1)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Results per page (default: 20, max: 100)
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// TaskType Filter by task type
	TaskType *string `form:"task_type,omitempty" json:"task_type,omitempty"`
}

// GetRepositoriesParams defines parameters for GetRepositories.
type GetRepositoriesParams struct {
	// Page Page number (default: 1)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Results per page (default: 20, max: 100)
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetRepositoriesIdCommitsParams defines parameters for GetRepositoriesIdCommits.
type GetRepositoriesIdCommitsParams struct {
	// Page Page number (default: 1)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Results per page (default: 20, max: 100)
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetRepositoriesIdCommitsCommitShaEnrichmentsParams defines parameters for GetRepositoriesIdCommitsCommitShaEnrichments.
type GetRepositoriesIdCommitsCommitShaEnrichmentsParams struct {
	// EnrichmentType Filter by enrichment type
	EnrichmentType *string `form:"enrichment_type,omitempty" json:"enrichment_type,omitempty"`

	// EnrichmentSubtype Filter by enrichment subtype
	EnrichmentSubtype *string `form:"enrichment_subtype,omitempty" json:"enrichment_subtype,omitempty"`

	// Page Page number (default: 1)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Results per page (default: 20, max: 100)
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetRepositoriesIdCommitsCommitShaFilesParams defines parameters for GetRepositoriesIdCommitsCommitShaFiles.
type GetRepositoriesIdCommitsCommitShaFilesParams struct {
	// Page Page number (default: 1)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Results per page (default: 20, max: 100)
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetRepositoriesIdCommitsCommitShaSnippetsParams defines parameters for GetRepositoriesIdCommitsCommitShaSnippets.
type GetRepositoriesIdCommitsCommitShaSnippetsParams struct {
	// Page Page number (default: 1)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Results per page (default: 20, max: 100)
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetRepositoriesIdEnrichmentsParams defines parameters for GetRepositoriesIdEnrichments.
type GetRepositoriesIdEnrichmentsParams struct {
	// EnrichmentType Filter by enrichment type
	EnrichmentType *string `form:"enrichment_type,omitempty" json:"enrichment_type,omitempty"`

	// MaxCommitsToCheck Max commits to check (default: 100)
	MaxCommitsToCheck *int `form:"max_commits_to_check,omitempty" json:"max_commits_to_check,omitempty"`

	// Page Page number (default: 1)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Results per page (default: 20, max: 100)
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetRepositoriesIdTagsParams defines parameters for GetRepositoriesIdTags.
type GetRepositoriesIdTagsParams struct {
	// Page Page number (default: 1)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Results per page (default: 20, max: 100)
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// PatchEnrichmentsIdJSONRequestBody defines body for PatchEnrichmentsId for application/json ContentType.
type PatchEnrichmentsIdJSONRequestBody = DtoEnrichmentUpdateRequest

// PostRepositoriesJSONRequestBody defines body for PostRepositories for application/json ContentType.
type PostRepositoriesJSONRequestBody = DtoRepositoryCreateRequest

// PutRepositoriesIdTrackingConfigJSONRequestBody defines body for PutRepositoriesIdTrackingConfig for application/json ContentType.
type PutRepositoriesIdTrackingConfigJSONRequestBody = DtoTrackingConfigUpdateRequest

// PostSearchJSONRequestBody defines body for PostSearch for application/json ContentType.
type PostSearchJSONRequestBody = DtoSearchRequest
