// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/enrichments": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "List enrichments with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enrichments"
                ],
                "summary": "List enrichments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by enrichment type",
                        "name": "enrichment_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by enrichment subtype",
                        "name": "enrichment_subtype",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Results per page (default: 20, max: 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.EnrichmentJSONAPIListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/enrichments/{id}": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Get an enrichment by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "enrichments"
                ],
                "summary": "Get enrichment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Enrichment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.EnrichmentJSONAPIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/queue": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "List tasks in the queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queue"
                ],
                "summary": "List tasks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Max results (default: 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by task type",
                        "name": "task_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TaskListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/queue/{task_id}": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Get a task by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queue"
                ],
                "summary": "Get task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TaskResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Get all tracked Git repositories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List repositories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.RepositoryListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Add a new Git repository to track",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Add repository",
                "parameters": [
                    {
                        "description": "Repository request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.RepositoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.RepositoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Get a repository by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Get repository",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.RepositoryResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Delete a repository by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Delete repository",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/commits": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "List commits for a repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List commits",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.CommitJSONAPIListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/commits/{commit_sha}": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Get a commit by SHA",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Get commit",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Commit SHA",
                        "name": "commit_sha",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.CommitJSONAPIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/commits/{commit_sha}/embeddings": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "List embeddings for snippets in a commit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List commit embeddings",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Commit SHA",
                        "name": "commit_sha",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Return full embedding vectors",
                        "name": "full",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.EmbeddingJSONAPIListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/commits/{commit_sha}/enrichments": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "List enrichments for a commit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List commit enrichments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Commit SHA",
                        "name": "commit_sha",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by enrichment type",
                        "name": "enrichment_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by enrichment subtype",
                        "name": "enrichment_subtype",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.EnrichmentJSONAPIListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/commits/{commit_sha}/enrichments/{enrichment_id}": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Get an enrichment by ID within commit context",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Get commit enrichment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Commit SHA",
                        "name": "commit_sha",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Enrichment ID",
                        "name": "enrichment_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.EnrichmentJSONAPIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/commits/{commit_sha}/files": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "List files for a commit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List commit files",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Commit SHA",
                        "name": "commit_sha",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.FileJSONAPIListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/commits/{commit_sha}/files/{blob_sha}": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Get a file by blob SHA",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Get commit file",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Commit SHA",
                        "name": "commit_sha",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Blob SHA",
                        "name": "blob_sha",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.FileJSONAPIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/commits/{commit_sha}/rescan": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Trigger a rescan of a specific commit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Rescan commit",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Commit SHA",
                        "name": "commit_sha",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/commits/{commit_sha}/snippets": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Redirects to enrichments endpoint with snippet filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List commit snippets",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Commit SHA",
                        "name": "commit_sha",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "308": {
                        "description": "Permanent Redirect"
                    }
                }
            }
        },
        "/repositories/{id}/enrichments": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "List recent enrichments across commits for a repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List repository enrichments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by enrichment type",
                        "name": "enrichment_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max commits to check (default: 100)",
                        "name": "max_commits_to_check",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Results per page (default: 20, max: 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.EnrichmentJSONAPIListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/status": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Get indexing task status for a repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Get repository status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TaskStatusListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/status/summary": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Get aggregated indexing status summary for a repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Get repository status summary",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.RepositoryStatusSummaryResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/tags": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "List tags for a repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "List tags",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TagJSONAPIListResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/tags/{tag_id}": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Get a tag by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Get tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tag ID",
                        "name": "tag_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TagJSONAPIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/repositories/{id}/tracking-config": {
            "get": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Get current tracking configuration for a repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Get tracking config",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Update tracking configuration for a repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repositories"
                ],
                "summary": "Update tracking config",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tracking config",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search": {
            "post": {
                "security": [
                    {
                        "APIKeyAuth": []
                    }
                ],
                "description": "Hybrid search across code snippets and enrichments",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search code",
                "parameters": [
                    {
                        "description": "Search request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.SearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_helixml_kodit_internal_api_v1_dto.CommitAttributes": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "commit_sha": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "parent_commit_sha": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.CommitData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.CommitAttributes"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.CommitJSONAPIListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.CommitData"
                    }
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.CommitJSONAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.CommitData"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.EmbeddingAttributes": {
            "type": "object",
            "properties": {
                "embedding": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "embedding_type": {
                    "type": "string"
                },
                "snippet_sha": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.EmbeddingData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.EmbeddingAttributes"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.EmbeddingJSONAPIListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.EmbeddingData"
                    }
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.EnrichmentAttributes": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "subtype": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.EnrichmentData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.EnrichmentAttributes"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.EnrichmentJSONAPIListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.EnrichmentData"
                    }
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.EnrichmentJSONAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.EnrichmentData"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.EnrichmentSchema": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.FileAttributes": {
            "type": "object",
            "properties": {
                "blob_sha": {
                    "type": "string"
                },
                "extension": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.FileData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.FileAttributes"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.FileJSONAPIListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.FileData"
                    }
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.FileJSONAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.FileData"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.GitFileSchema": {
            "type": "object",
            "properties": {
                "blob_sha": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.RepositoryAttributes": {
            "type": "object",
            "properties": {
                "cloned_path": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "last_scanned_at": {
                    "type": "string"
                },
                "num_branches": {
                    "type": "integer"
                },
                "num_commits": {
                    "type": "integer"
                },
                "num_tags": {
                    "type": "integer"
                },
                "remote_uri": {
                    "type": "string"
                },
                "tracking_branch": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.RepositoryData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.RepositoryAttributes"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.RepositoryListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.RepositoryData"
                    }
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.RepositoryRequest": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "commit": {
                    "type": "string"
                },
                "remote_url": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.RepositoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.RepositoryData"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.RepositoryStatusSummaryAttributes": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.RepositoryStatusSummaryData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.RepositoryStatusSummaryAttributes"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.RepositoryStatusSummaryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.RepositoryStatusSummaryData"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.SearchAttributes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "filters": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.SearchFilters"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.SearchData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.SearchAttributes"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.SearchFilters": {
            "type": "object",
            "properties": {
                "authors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "commit_sha": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "end_date": {
                    "type": "string"
                },
                "enrichment_subtypes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "enrichment_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "file_patterns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.SearchRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.SearchData"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.SearchResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.SnippetData"
                    }
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.SnippetAttributes": {
            "type": "object",
            "properties": {
                "content": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.SnippetContentSchema"
                },
                "created_at": {
                    "type": "string"
                },
                "derives_from": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.GitFileSchema"
                    }
                },
                "enrichments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.EnrichmentSchema"
                    }
                },
                "original_scores": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.SnippetContentSchema": {
            "type": "object",
            "properties": {
                "language": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.SnippetData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.SnippetAttributes"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TagAttributes": {
            "type": "object",
            "properties": {
                "commit_sha": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TagData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TagAttributes"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TagJSONAPIListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TagData"
                    }
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TagJSONAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TagData"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TaskAttributes": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "payload": {},
                "priority": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TaskData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TaskAttributes"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TaskListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TaskData"
                    }
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TaskResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TaskData"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TaskStatusAttributes": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "current": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "progress": {
                    "type": "number"
                },
                "state": {
                    "type": "string"
                },
                "step": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TaskStatusData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TaskStatusAttributes"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TaskStatusListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TaskStatusData"
                    }
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigAttributes": {
            "type": "object",
            "properties": {
                "mode": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TrackingMode"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigAttributes"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigData"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigUpdateAttributes": {
            "type": "object",
            "properties": {
                "mode": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TrackingMode"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigUpdateData": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigUpdateAttributes"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigUpdateRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_helixml_kodit_internal_api_v1_dto.TrackingConfigUpdateData"
                }
            }
        },
        "github_com_helixml_kodit_internal_api_v1_dto.TrackingMode": {
            "type": "string",
            "enum": [
                "branch",
                "tag"
            ],
            "x-enum-varnames": [
                "TrackingModeBranch",
                "TrackingModeTag"
            ]
        }
    },
    "securityDefinitions": {
        "APIKeyAuth": {
            "type": "apiKey",
            "name": "X-API-KEY",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Kodit API",
	Description:      "Code understanding platform with hybrid search and LLM-powered enrichments",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
