# ruff: noqa
"""add commit_snippets_v2 association table

Revision ID: 5d3d21b2753f
Revises: e90ec027c388
Create Date: 2025-09-15 13:04:44.103503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3d21b2753f'
down_revision: Union[str, None] = 'e90ec027c388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commit_snippets_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('snippet_sha', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['commit_sha'], ['git_commits.commit_sha'], ),
    sa.ForeignKeyConstraint(['snippet_sha'], ['snippets_v2.sha'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commit_sha', 'snippet_sha', name='uix_commit_snippet')
    )
    op.create_index(op.f('ix_commit_snippets_v2_commit_sha'), 'commit_snippets_v2', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_commit_snippets_v2_snippet_sha'), 'commit_snippets_v2', ['snippet_sha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commit_snippets_v2_snippet_sha'), table_name='commit_snippets_v2')
    op.drop_index(op.f('ix_commit_snippets_v2_commit_sha'), table_name='commit_snippets_v2')
    op.drop_table('commit_snippets_v2')
    # ### end Alembic commands ###
