# ruff: noqa
"""add snippet processing state

Revision ID: 7f2fdf39b770
Revises: b9cd1c3fd762
Create Date: 2025-09-10 12:12:17.962909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f2fdf39b770"
down_revision: Union[str, None] = "b9cd1c3fd762"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snippet_processing_states",
        sa.Column("snippet_id", sa.Integer(), nullable=False),
        sa.Column("processing_step", sa.String(length=100), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["snippet_id"], ["snippets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "snippet_id", "processing_step", name="uix_snippet_processing_step"
        ),
    )
    op.create_index(
        op.f("ix_snippet_processing_states_processing_step"),
        "snippet_processing_states",
        ["processing_step"],
        unique=False,
    )
    op.create_index(
        op.f("ix_snippet_processing_states_snippet_id"),
        "snippet_processing_states",
        ["snippet_id"],
        unique=False,
    )
    op.add_column(
        "snippets", sa.Column("content_hash", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_snippets_content_hash"), "snippets", ["content_hash"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_snippets_content_hash"), table_name="snippets")
    op.drop_column("snippets", "content_hash")
    op.drop_index(
        op.f("ix_snippet_processing_states_snippet_id"),
        table_name="snippet_processing_states",
    )
    op.drop_index(
        op.f("ix_snippet_processing_states_processing_step"),
        table_name="snippet_processing_states",
    )
    op.drop_table("snippet_processing_states")
    # ### end Alembic commands ###
